[package]
name = "whippit"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
clap = { version = "4.4.2", features = ["derive"] }
env_logger = "0.10.0"
indexmap = "2.0.0"
log = "0.4.20"
miette = { version = "5.10.0", features = ["fancy"] }
path-dsl = "0.6.1"
regex = "1.9.5"
thiserror = "1.0.49"

[dev-dependencies]
insta = "1.33.0"
